server.port=5555

#DataSource

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/otpdb
spring.datasource.username=root
spring.datasource.password=kumar123

#hikardatsource
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.connection-timeout=200000

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Logger
logging.level.root=info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
#logging.pattern.console=% -5%level %logger{36} -%m -%n
